component: scf
app: art
name: art-tf
stage: dev

inputs:
  src:
    src: ./
    exclude:
      - .env
      - model
      - node_modules/**
  # 此处注释部分将自动使用默认值
  region: ap-guangzhou
  name: ${name}
  runtime: Nodejs10.15
  memorySize: 3072 # 内存大小，单位MB
  timeout: 60 # 超时时间，单位秒
  environment: #  环境变量
    variables: #  环境变量对象
      NODE_ENV: production
  handler: index.main_handler
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: POST
